import { StyleSheet } from "react-native";
import { fontsFamily, colors } from "../../shared/globalStyles";

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#000000',
    flex: 1,
  },
  header: {
    height: 60,
    backgroundColor: '#050505',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  headerContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerText: {
    flex: 1,
    alignItems: 'center',
  },
  headerButton: {
    position: 'relative',
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    bottom: -5,
    right: 0,
    backgroundColor: '#555555',
    color: '#FFFFFF',
    fontFamily: fontsFamily.regular,
    fontSize: 8,
    paddingHorizontal: 5,
    borderRadius: 2,
  },
  headerTitle: {
    color: '#FFFFFF',
    fontFamily: fontsFamily.regular,
    fontSize: 16,
  },
  subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
  },
  headerAvatar: {
    width: 18,
    height: 18,
    borderRadius: 10,
    overflow: 'hidden',
    marginLeft: 7,
    marginRight: 3,
  },
  headerSubtitle: {
    color: '#FFFFFF',
    opacity: 0.5,
    fontSize: 12,
    fontFamily: fontsFamily.regular,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  language: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
  },
  languageTitle: {
    color: '#FFFFFF',
    opacity: .5,
    fontSize: 12,
    fontFamily: fontsFamily.regular,
    textTransform: 'uppercase',
  },
  languageContent: {
    color: '#FFFFFF',
    fontSize: 20,
    marginLeft: 5,
    fontFamily: fontsFamily.bold,
  },
  description: {
    color: '#FFFFFF',
    opacity: 0.8,
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    fontFamily: fontsFamily.regular,
    marginBottom: 15,
    opacity: 0.8,
  },
  repoDates: {
    marginVertical: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  dateItem: {
    flex: 1,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 7,
  },
  mainDateItem: {
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 7,
  },
  dateItemTitle: {
    color: '#FFFFFF',
    fontSize: 10,
    fontFamily: fontsFamily.regular,
    textTransform: 'uppercase',
    opacity: .5,
  },
  dataItemContent: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: fontsFamily.regular,
    marginTop: 5,
  },
  moreInfo: {
    marginVertical: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoBox: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoIcon: {
    height: 38,
  },
  infoTitle: {
    color: '#FFFFFF',
    textTransform: 'uppercase',
    opacity: 0.5,
    fontSize: 12,
    fontFamily: fontsFamily.regular,
    marginBottom: 3,
  },
  infoValue: {
    color: '#FFFFFF',
    fontFamily: fontsFamily.regular,
    fontSize: 16,
  },
  contentUtilities: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  contentUtilitiesItem: {
    marginHorizontal: 5,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  contentIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});